name: demo-action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.6.0  # Correct version for checkout
      - name: Run as sample job
        run: echo "This is a sample job running after code checkout"

      - name: Create a sample file
        run: echo "This is a sample file" > sample.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: sample-artifact
          path: sample.txt
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/download-artifact@v4.6.0
        with:
          name: build=artifact
          path: ${{github.workspace}}
