name: demo-action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Correct version for checkout
      - name: Run as sample job
        run: echo "This is a sample job running after code checkout"
