name: Upload Artifact Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build project
        run: |
          mkdir -p build
          echo "Build successful!" > build/output.txt
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build/
